# Generated by Django 5.2.7 on 2025-10-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=45)),
                ('datanasc_aluno', models.DateField(db_column='dataNasc_aluno')),
                ('cpf_aluno', models.CharField(max_length=11)),
                ('obs_aluno', models.TextField(blank=True, null=True)),
                ('id_turma', models.IntegerField()),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('nome_turma', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'turma',
                'managed': False,
            },
        ),
    ]
